### ISSUE TITLE
Mistake in tutorial part2 - Creating a depth shader

### ISSUE THREAD

**Issue by playmyskay** [haedri/shadow-mapping#3]
In my opinion your tutorial of "part2" contains a mistake.

See topic "Creating a depth shader":

Your fragment shader has the following line:
> gl_FragColor    = vec4(length(v_position.xyz-u_lightPosition)/u_cameraFar);

... and you said:
> A darker pixel means the point is farther away from the camera.

But it is the other way round, it is more brighter if the point is farther away.
For instance, "v_position.xyz-u_lightPosition" would be 10 and u_cameraFar would be 10 too. than the result is 10/10 = 1.. the farthest distance possible. This will give us vec4(1.0f) seen as Color (gl_FragColor) would be white, rgba(255,255,255,255).

So your supporting image is also not correct.

Regarding to your source code example the result depthmap-image is also like my assumption.

See my attached image file;

![screenshot_depthmap_1](https://cloud.githubusercontent.com/assets/3920264/20856203/952fb40e-b909-11e6-9d2a-171151de31a1.png)

So this part of your tutorial is a little confusing and finally not correct.. it costs me a few hours to find out ;-)

Nevertheless, thank you 'lot for this tutorial!

**Comment by haedri** [comment]
Thanks for reporting this issue, and sorry for the very long delay
It seems you are right, but since this is old code I have no idea why I wrote that. It seems from the screenshot in the wiki that at some point this sentence was true... No idea why I inverted the logic though
Guess I'll have to redo all screenshots :)

**Comment by haedri** [comment]
Ok, that was an easy fix finally
It's just that the depth shader also changes the alpha component, and I didn't notice it, so with a small alpha value the white background on github made the colors appear inverted... and I guess it confused me
Thanks !
